version: '3.5'

services:

  # Services
  consignment:
    restart: always
    build: ./service-consignment
    depends_on:
#      - datastore
      - vessel
    ports:
      - "50051:50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "postgres://postgres:1234@datastore:5432/microservice"

  vessel:
    restart: always
    build: ./service-vessel
    ports:
      - "50052:50051"
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "postgres://postgres:1234@datastore:5432/microservice"

  # Database tier
  datastore:
    image: postgres
    container_name: "datastore"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: microservice
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"